services:
  daily-diet-db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'admin123'
      MYSQL_DATABASE: 'daily-diet-db'
      MYSQL_ROOT_PASSWORD: 'admin123'
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - /Users/caduguerra/Desktop/Cursos/python/daily-diet-mysql:/var/lib/mysql